#!/usr/bin/python

# How many days ago was a particular date?
# script dd mm yy

from datetime import date
import sys

now = date.today()
month = int(sys.argv[1])
day = int(sys.argv[2])
year = int(sys.argv[3])
try:
    if 50 <= year < 100:    # assume 20th century
        year += 1900
    if 0 <= year < 50:      # assume 21st century
        year += 2000
except IndexError:          # assume this year
    year = now.year

then = date(year, month, day)
ago = now - then
print ago.days
