#!/bin/bash

# Displays the 10 largest files in the specified directory.
# Uses current directory by default.

# Ignore files in .git.
find "${1-.}" -not -iwholename '*.git*' -printf '%s %p\n'| sort -nr | head -10
