#!/bin/bash

# Clear the screen. I usually alias this in .bashrc.

if [ "$(uname)" == "Darwin" ]; then
    clear
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    clear
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    printf "\033c"
fi
