#!/bin/bash

# Counts the number of files in each directory.

find . -type d -not -iwholename '*.git*' -print0 | while read -d '' -r dir; do
    files=("$dir"/*)
    printf "%5d files in directory %s\n" "${#files[@]}" "$dir"
done
