#!/bin/bash

shopt -s extglob

# Flatten and clean up the TV folder.
find /cygdrive/c/dl/torrent -mindepth 2 -type f -name '*.mkv' -exec mv -i '{}' /cygdrive/c/dl/torrent/tv\ -\ complete ';'
find /cygdrive/c/dl/torrent -mindepth 2 -type f -name '*.mp4' -exec mv -i '{}' /cygdrive/c/dl/torrent/tv\ -\ complete ';'
find /cygdrive/c/dl/torrent/ -type d -not -name torrent -not -name tv\ -\ complete -exec rm -R {} \;
