#!/bin/bash
# Writes a list of my movies and TV shows.

dst='/home/misc/Dropbox/logs'

if [ "$(uname)" == "Darwin" ]; then
    echo "configure this"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    echo "configure this"
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    dst='/cygdrive/c/Dropbox/logs'
fi

tree /media/external/videos/Movies/ > $dst/movies.txt
tree /media/external/videos/TV\ Shows/ > $dst/tv_shows.txt
tree /home/misc/Dropbox/books/ > $dst/books.txt
