#!/bin/bash
# Writes a list of my movies and TV shows.

dst='/home/misc/Dropbox/logs'

tree /media/external/videos/Movies/ > $dst/movies.txt
tree /media/external/videos/TV\ Shows/ > $dst/tv_shows.txt
tree /home/misc/Dropbox/books/ > $dst/books.txt
