#!/bin/bash

cmd='rsync --ignore-missing-args -a --no-owner --no-group --remove-source-files'

if [ "$(uname)" == "Darwin" ]; then
    echo "configure this"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    src="/home/misc/windows/dl/MoveToPlex/"
    dst="/media/external/videos/Movies"
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    src="/cygdrive/c/dl/MoveToPlex/"
    dst="/cygdrive/j/videos/Movies"
fi

$cmd $src $dst
