#!/bin/bash

# Hack to get videos from my Windows machine to the correct locations.
# Add this to Startup Applications.

src="/home/misc/windows/dl/MoveToPlex/"
dst="/media/external/videos/Movies"
cmd='rsync --ignore-missing-args -a --no-owner --no-group --remove-source-files'

$cmd $src $dst
