#!/bin/bash

# Hack to get videos from my Windows machine to the correct locations.
# Add this to Startup Applications.

# Movies.
mv /media/misc/OS/dl/MoveToPlex/MoviesCollection/* /media/external/videos/Movies/Collection/
mv /media/misc/OS/dl/MoveToPlex/MoviesFavorites/* /media/external/videos/Movies/Favorites/
mv /media/misc/OS/dl/MoveToPlex/MoviesNeverWatched/* /media/external/videos/Movies/Never\ Watched/
