#!/bin/bash

# Move nzb files to proper directory.

if [ "$(uname)" == "Darwin" ]; then
    echo "configure this"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    mv ~/Downloads/*.nzb /home/misc/windows/dl/torrent_source
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    echo "configure this"
fi
