#!/bin/sh

# This allows me to keep notes in one location from the command line. 
# It can be used to log work.
# Ex: note date          - inserts today's date
# Ex: note "something"   - inserts the note "something" into the file

cmd=$1
dt=`date +%m-%d-%y`

if [ "$(uname)" == "Darwin" ]; then
    # file='path to file'
    echo "Configure this."
    exit 
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    # file='path to file'
    echo "Configure this."
    exit
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    file='/cygdrive/c/home/notes/done.txt'
fi

if [  "$1" == "date" ]; then
    printf "\n$dt\n" >> $file 
    echo "--------" >> $file
else
    printf "$cmd\n" >> $file
fi

