#!/bin/bash

# This allows me to keep notes in one location from the command line. 
# I'm using it to log work.
# Ex: note date          - inserts today's date
# Ex: note "something"   - inserts the note "something" into the file
 
cmd=$1
dt=`date +%m-%d-%y`

if [ "$(uname)" == "Darwin" ]; then
    # file='path to file'
    echo "Configure this.";
    exit;
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    file='/home/misc/Dropbox/notes/notes.txt'
    #echo "Configure this.";
    #exit;
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    file='/cygdrive/c/home/notes/done.txt'
fi

if [  "$1" == "date" ]; then
    printf "\n$dt\n" >> $file 
    echo "--------" >> $file
elif [  "$1" == "tail" ]; then
    tail $file 
elif [  "$1" == "today" ]; then
    echo ""
    sed -n "/$dt/,//p" $file
elif [  "$1" == "list" ] || [  "$1" == "lsit" ]; then
    cat $file 
elif [  "$1" == "star" ] || [ "$1" == "todo" ] ; then
    note list | grep --color "\*" 
elif [  "$1" == "" ]; then
    vim $file 
else
    printf "$cmd\n" >> $file
fi

