#!/bin/bash

# Open file from command line.

if [ "$(uname)" == "Darwin" ]; then
    echo "configure this"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    xdg-open "$1"
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    cygstart "$1"
fi
