#!/bin/bash

# Start local webserver using Python to share current directory.

if [ "$(uname)" == "Darwin" ]; then
    echo "Configure me" 
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    current_ip="$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')"
    echo $current_ip:8000
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    echo $(getlocalip):8000
fi

python -m SimpleHTTPServer
