#!/bin/bash
# Wrapper for youtube-dl that directly creates mp3s.

# https://trac.ffmpeg.org/wiki/Encode/MP3
# lame option    Average kbit/s    Bitrate range kbit/s    ffmpeg/avconv option
#       -V 0        245                  220-260                -q:a 0
#       -V 1        225                  190-250                -q:a 1
#       -V 2        190                  170-210                -q:a 2
#       -V 3        175                  150-195                -q:a 3
#       -V 4        165                  140-185                -q:a 4
#       -V 5        130                  120-150                -q:a 5
#       -V 6        115                  100-130                -q:a 6
#       -V 7        100                   80-120                -q:a 7
#       -V 8        85                    70-105                -q:a 8
#       -V 9        65                     45-85                -q:a 9

cmd='youtube-dl --extract-audio --audio-format mp3 --audio-quality 2 --download-archive '

# Configuration options.
if [ "$(uname)" == "Darwin" ]; then
    echo "configure this"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    src='~/Dropbox/logs/youtube/youtube-source-audio.txt'
    archive='~/Dropbox/logs/youtube/youtube-archive-audio.txt'
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    src='c:\Dropbox\logs\youtube\youtube-source-audio.txt'
    archive='c:\Dropbox\logs\youtube\youtube-archive-audio.txt'
fi

if [ "$1" == "list" ]; then
    $cmd $archive --batch-file=$src
elif [ "$1" == "edit" ]; then
    vim $src
else
    $cmd $archive "$1"
fi
