#!/bin/bash
# Wrapper for youtube-dl that directly creates mp3s.

cmd='youtube-dl --extract-audio --audio-format mp3 --audio-quality 2'

# Configuration options.
if [ "$(uname)" == "Darwin" ]; then
    echo "configure this"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    src='~/Dropbox/youtube/youtube.txt'
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    src='c:\Dropbox\youtube\youtube.txt'
fi

if [ "$1" == "file" ]; then
    $cmd --batch-file=$src
elif [ "$1" == "edit" ]; then
    vim $src
else
    $cmd "$1"
fi
