#!/bin/bash
# Wrapper for youtube-dl.

download_playlist='https://www.youtube.com/playlist?list=PL1wufWAX7DrLfSXMxM8t_RhWdLSpM3oq1'

# Configuration options/
if [ "$(uname)" == "Darwin" ]; then
    echo "configure this"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    src='~/Dropbox/youtube/youtube-video.txt'
    archive='~/Dropbox/youtube/youtube-archive-video.txt'
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    src='c:\Dropbox\youtube\youtube-video.txt'
    archive='c:\Dropbox\youtube\youtube-archive-video.txt'
fi

if [ "$1" == "list" ]; then
    youtube-dl --batch-file=$src --download-archive $archive
elif [ "$1" == "edit" ]; then
    vim $src
elif [ "$1" == "dl" ]; then
    youtube-dl --download-archive $archive $download_playlist
fi
