#!/bin/bash
# Wrapper for youtube-dl.
# yt <URL>: download URL/playlist
# yt edit: edit file
# yt: download from saved download playlist

download_playlist='https://www.youtube.com/playlist?list=PL1wufWAX7DrLfSXMxM8t_RhWdLSpM3oq1'

# Configuration options/
if [ "$(uname)" == "Darwin" ]; then
    echo "configure this"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    src='~/Dropbox/youtube/youtube.txt'
    archive='~/Dropbox/youtube/youtube-archive.txt'
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    src='c:\Dropbox\youtube\youtube.txt'
    archive='c:\Dropbox\youtube\youtube-archive.txt'
fi

# Uses.
if [ "$1" == "file" ]; then
    youtube-dl --batch-file=$src
elif [ "$1" == "edit" ]; then
    vim $src
elif [ "$1" == "" ]; then
    youtube-dl --download-archive $archive $download_playlist
fi
