#!/bin/bash
# Wrapper for youtube-dl.
# It handles 2 scenarios:
#   1) Download a list of videos.
#   2) Edit the list videos.


if [ "$(uname)" == "Darwin" ]; then
    echo "configure this"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    src='~/Dropbox/youtube.txt'
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    src='c:\Dropbox\youtube.txt'
fi


# Download from existing list. 
if [ "$1" == "dl" ]; then
    youtube-dl --batch-file=$src
# Edit the list if nothing is specified.
elif [ "$1" == "" ]; then
    vim $src
fi
